# Generated by Django 3.1.4 on 2020-12-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('portal', '0002_auto_20201220_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
