# Generated by Django 3.1.4 on 2020-12-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20201227_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpost',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
